-- Temporarily disable RLS for migration
-- WARNING: Only run this in development/staging environments

-- Disable RLS on all tables
ALTER TABLE exams DISABLE ROW LEVEL SECURITY;
ALTER TABLE topics DISABLE ROW LEVEL SECURITY;
ALTER TABLE topic_modules DISABLE ROW LEVEL SECURITY;
ALTER TABLE questions DISABLE ROW LEVEL SECURITY;
ALTER TABLE certification_info DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_exam_sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE session_questions DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_answers DISABLE ROW LEVEL SECURITY;
ALTER TABLE exam_results DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_preferences DISABLE ROW LEVEL SECURITY;

-- After migration, re-enable RLS with:
-- ALTER TABLE exams ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE topics ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE topic_modules ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE questions ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE certification_info ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE user_exam_sessions ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE session_questions ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE user_answers ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE exam_results ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE user_preferences ENABLE ROW LEVEL SECURITY;
