#!/usr/bin/env tsx
/**
 * Reads public content tables from the linked Supabase project via the anon key
 * and writes supabase/seed.sql. Run whenever the upstream content changes:
 *   npm run seed:generate
 */

import { createClient } from '@supabase/supabase-js';
import * as dotenv from 'dotenv';
import * as fs from 'fs';
import * as path from 'path';

dotenv.config({ path: '.env.local' });

const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
const key = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!url || !key) {
  console.error('Missing NEXT_PUBLIC_SUPABASE_URL or a key in .env.local');
  process.exit(1);
}

const supabase = createClient(url, key, {
  auth: { autoRefreshToken: false, persistSession: false },
});

const CONTENT_TABLES = [
  'exams',
  'topics',
  'topic_modules',
  'questions',
  'certification_info',
] as const;

const PAGE = 1000;

async function fetchAll(table: string): Promise<Record<string, unknown>[]> {
  const rows: Record<string, unknown>[] = [];
  let from = 0;
  while (true) {
    const to = from + PAGE - 1;
    const { data, error } = await supabase.from(table).select('*').range(from, to);
    if (error) throw new Error(`${table}: ${error.message}`);
    if (!data || data.length === 0) break;
    rows.push(...data);
    if (data.length < PAGE) break;
    from += PAGE;
  }
  return rows;
}

function quote(value: unknown): string {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'boolean') return value ? 'TRUE' : 'FALSE';
  if (typeof value === 'number') return String(value);
  if (value instanceof Date) return `'${value.toISOString()}'`;
  if (typeof value === 'object') {
    return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
  }
  return `'${String(value).replace(/'/g, "''")}'`;
}

function toInsert(table: string, rows: Record<string, unknown>[]): string {
  if (rows.length === 0) return `-- ${table}: no rows\n\n`;
  const cols = Object.keys(rows[0]);
  const header = `-- ${table} (${rows.length} rows)\n`;
  const body = rows
    .map(
      (r) =>
        `INSERT INTO ${table} (${cols.join(', ')}) VALUES (${cols
          .map((c) => quote(r[c]))
          .join(', ')}) ON CONFLICT DO NOTHING;`,
    )
    .join('\n');
  return `${header}${body}\n\n`;
}

async function main() {
  const outPath = path.join(process.cwd(), 'supabase', 'seed.sql');
  const parts: string[] = [
    '-- Generated by scripts/generate-seed.ts — do not edit by hand',
    `-- Generated: ${new Date().toISOString()}`,
    '-- Source: ' + url,
    '',
    'BEGIN;',
    '',
  ];

  for (const table of CONTENT_TABLES) {
    process.stdout.write(`fetching ${table}... `);
    const rows = await fetchAll(table);
    console.log(`${rows.length} rows`);
    parts.push(toInsert(table, rows));
  }

  parts.push('COMMIT;', '');
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, parts.join('\n'));
  console.log(`\nwrote ${outPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
